### ISSUE TITLE
Timeline does not work properly

### ISSUE THREAD

**Issue by koilebeit** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#165]
### Current Behavior

The first row of the timeline shows all possible objects with different dates

### Steps To Reproduce

1. go to [https://forschung.stadtgeschichtebasel.ch/timeline.html](https://forschung.stadtgeschichtebasel.ch/timeline.html)
2. see first row

### Anything else?

It may have to do with the inability of timeline to handle all edtf data. possibly especially BC dates

**Comment by maehr** [comment]
### Issue: Timeline Date Handling Error for Negative and Incorrect Date Formats

**Description**
In the current timeline view at [Stadtgeschichte Basel Timeline](https://forschung.stadtgeschichtebasel.ch/timeline.html), dates are not displayed correctly. Specifically:

1. The timeline does not handle negative dates (BCE dates) properly.
2. The platform requires specific formatting for years:
   - Years must have four digits, or be represented by "X" if unknown.
   - Formatting rules include:
     - 100 BC should be formatted as `-0100`
     - 12500 BC as `Y-12500`
     - 500 AD as `0500`

However, the timeline currently does not support negative year values, causing issues with BCE dates.

**Steps to Reproduce**
1. Upload date entries including BCE years and view the timeline.
2. Observe that BCE dates and potentially other incorrectly formatted dates are not displayed as expected.

**Expected Behavior**
- Timeline should support BCE dates (negative year values) as well as AD dates, displaying them in proper chronological order.

**Potential Solutions**
1. **Fix Date Format Handling**: Ensure all years include at least four digits, padding with zeros where necessary.
2. **Enable Negative Year Support**: Modify timeline parsing logic to accommodate negative values for BCE dates.
3. **Additional Investigation**: Further testing is recommended to identify any other potential date format inconsistencies.

**Next Steps**
- **Action**: Investigate and implement support for negative values in the timeline component.

**Reported by**: Cristina Muench & @koilebeit 
**Date**: October 27, 2024
